name: Example CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  EXAMPLE_VALUE: JoinMe

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo 'You just interacted with and action on ${{ env.EXAMPLE_VALUE }}'

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: build
        run: npm run heroku-postbuild
      
