name: PR to develop check

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:
      SESSION_SECRET: ${{ secrets.SESSION_SECRET}}
      SESSION_NAME: ${{ secrets.SESSION_NAME}}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      PORT: ${{ secrets.PORT}}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
      GOOGLE_APIS_KEY: ${{ secrets.GOOGLE_APIS_KEY}}
      PG_USER: ${{ secrets.PG_USER}}
      PG_HOST: ${{ secrets.PG_HOST}}
      PG_DB: ${{ secrets.PG_DB}}
      PG_PW: ${{ secrets.PG_PW}}
      PG_PORT: ${{ secrets.PG_PORT}}
      PG_URI: ${{ secrets.PG_URI}}
      PG_URI_LOCAL: ${{ secrets.PG_URI_LOCAL}}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET}}

    steps:
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-
            ${{ runner.os }}-
      - name: Install
        run: npm run install-all
      - name: Format, lint
        run: npm run format-all
      # - name: Test
      #   run: npm run test
      - name: Check postbuild (no install-client)
        run: npm run build-client && npm run build
